In [1]:
import requests
from bs4 import BeautifulSoup

In [4]:
url="https://www.flipkart.com/search?q=iphone&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"
req=requests.get(url)
soup=BeautifulSoup(req.content,'html.parser')

In [21]:
containers=soup.find_all(class_="_1-2Iqu row")
name=[container.find(class_="_3wU53n").get_text() for container in containers]
rating=[container.find(class_="hGSR34").get_text() for container in containers]
price=[container.find(class_="_1vC4OE _2rQ-NK").get_text() for container in containers]
rating

['4.5',
 '4.5',
 '4.5',
 '4.5',
 '4.5',
 '4.7',
 '4.7',
 '4.7',
 '4.5',
 '4.7',
 '4.5',
 '4.7',
 '4.7',
 '4.6',
 '4.5',
 '4.6',
 '4.7',
 '4.7',
 '4.7',
 '4.7',
 '4.7',
 '4.6',
 '4.6',
 '4.7']

In [23]:
import pandas as pd
flipkart_iphone_data=pd.DataFrame({'Product_name':name,'Product_rating':rating,'Product_price':price})
flipkart_iphone_data

,Product_name,Product_price,Product_rating
0,"Apple iPhone 7 (Black, 32 GB)","₹24,999",4.5
1,"Apple iPhone 7 (Gold, 32 GB)","₹24,999",4.5
2,"Apple iPhone 7 (Rose Gold, 32 GB)","₹24,999",4.5
3,"Apple iPhone 8 (Space Grey, 64 GB)","₹33,999",4.5
4,"Apple iPhone 8 (Gold, 64 GB)","₹33,999",4.5
5,"Apple iPhone 11 (White, 128 GB)","₹69,900",4.7
6,"Apple iPhone 11 (Black, 128 GB)","₹69,900",4.7
7,"Apple iPhone 11 (White, 64 GB)","₹64,900",4.7
8,"Apple iPhone 8 (Silver, 64 GB)","₹33,999",4.5
9,"Apple iPhone 11 (Black, 64 GB)","₹64,900",4.7
10,"Apple iPhone 6s (Space Grey, 32 GB)","₹23,999",4.5
11,"Apple iPhone 11 (Green, 64 GB)","₹64,900",4.7
12,"Apple iPhone 11 (Red, 64 GB)","₹64,900",4.7
13,"Apple iPhone XR (Black, 64 GB)","₹49,899",4.6
14,"Apple iPhone 6s (Gold, 32 GB)","₹23,999",4.5
15,"Apple iPhone XR (White, 64 GB)","₹49,899",4.6
16,"Apple iPhone 11 Pro (Midnight Green, 64 GB)","₹99,900",4.7
17,"Apple iPhone 11 Pro Max (Midnight Green, 64 GB)","₹1,09,900",4.7
18,"Apple iPhone 11 Pro (Gold, 64 GB)","₹99,900",4.7
19,"Apple iPhone 11 Pro Max (Silver, 64 GB)","₹1,09,900",4.7
20,"Apple iPhone 11 Pro (Silver, 64 GB)","₹99,900",4.7
21,"Apple iPhone 8 Plus (Gold, 256 GB)","₹64,900",4.6
22,"Apple iPhone XR (White, 128 GB)","₹59,999",4.6
23,"Apple iPhone 11 Pro (Silver, 256 GB)","₹1,13,900",4.7